### ISSUE TITLE
ClassCastException: ResString -> ResStringArray$Item, seperator problem

### ISSUE THREAD

**Issue by ludoux** [LonamiWebs/Stringlate#184]
## What happened?
Crashed.(FC)
## What have I done before crash happened?
I'm using ver 0.13 to translate this [repo](https://github.com/T-Rex96/Easy_xkcd).
Most translation can be typed and saved successfully. But when it came to pref_notifications:0 (current_string_id), after typing any character, the app crashed.
![img_20180311_120923](https://user-images.githubusercontent.com/13460812/37249576-33483642-2525-11e8-9a32-b2e01f26bd3c.jpg)

It also happened at pref_notifications:1/2/3 , pref_orientation:0/1/2 . It doesn't crash at loading_offline_20/80 which also contain numbers and I can translate them successfully.

## Device Info & Log

I'm using Unoffical Resurrection Remix Nougat(7.1.2) V5.8.5 LuisROM for OnePlus 3 [link](https://luis-builds.de/downloads/lineageos/rr/oneplus3/)

Built Time: 28. Feb CET 2018
```
#######RuntimeEnvironmentInformation#######
crash time=2018-03-11 12:14:09.911
model=ONEPLUS A3000
android version=7.1.2(25)
brand=OnePlus
manufacturer=OnePlus
board=msm8996
hardware=qcom
device=OnePlus3
version name=0.13
supported_abis=arm64-v8a & armeabi-v7a & armeabi
display=lineage_oneplus3-userdebug 7.1.2 NJH47F 40a6a51390 release-keys
#######ForceCloseCrashLog#######
FATAL EXCEPTION: main
Process: io.github.lonamiwebs.stringlate, PID: 19161
java.lang.ClassCastException: io.github.lonamiwebs.stringlate.classes.resources.tags.ResString cannot be cast to io.github.lonamiwebs.stringlate.classes.resources.tags.ResStringArray$Item
	at io.github.lonamiwebs.stringlate.classes.resources.Resources.setContent(Resources.java:164)
	at io.github.lonamiwebs.stringlate.activities.translate.TranslateActivity$7.onTextChanged(TranslateActivity.java:957)
	at android.widget.TextView.sendOnTextChanged(TextView.java:8187)
	at android.widget.TextView.handleTextChanged(TextView.java:8249)
	at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:10371)
	at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1263)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:507)
	at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:844)
	at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:617)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:408)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:93)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

´´´

**Comment by ludoux** [comment]
Well, every current_string_id ended with ":number" in that repo can cause FC.

**Comment by ludoux** [comment]
Btw, I can't export the . xml file of this repo to SD card. After clicking the save label, it crashed again.
```
#######RuntimeEnvironmentInformation#######
crash time=2018-03-11 14:54:57.596
model=ONEPLUS A3000
android version=7.1.2(25)
brand=OnePlus
manufacturer=OnePlus
board=msm8996
hardware=qcom
device=OnePlus3
version name=0.13
supported_abis=arm64-v8a & armeabi-v7a & armeabi
display=lineage_oneplus3-userdebug 7.1.2 NJH47F 40a6a51390 release-keys
#######ForceCloseCrashLog#######
FATAL EXCEPTION: main
Process: io.github.lonamiwebs.stringlate, PID: 27493
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=708, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/document/primary:strings0.xml flg=0x43 }} to activity {io.github.lonamiwebs.stringlate/io.github.lonamiwebs.stringlate.activities.translate.TranslateActivity}: java.lang.ClassCastException: io.github.lonamiwebs.stringlate.classes.resources.tags.ResString cannot be cast to io.github.lonamiwebs.stringlate.classes.resources.tags.ResStringArray$Item
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4141)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4184)
	at android.app.ActivityThread.-wrap20(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1563)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
Caused by: java.lang.ClassCastException: io.github.lonamiwebs.stringlate.classes.resources.tags.ResString cannot be cast to io.github.lonamiwebs.stringlate.classes.resources.tags.ResStringArray$Item
	at io.github.lonamiwebs.stringlate.classes.resources.ResourcesParser.writeReplaceStrings(ResourcesParser.java:603)
	at io.github.lonamiwebs.stringlate.classes.resources.ResourcesParser.applyTemplate(ResourcesParser.java:665)
	at io.github.lonamiwebs.stringlate.classes.repos.RepoHandler.applyTemplate(RepoHandler.java:443)
	at io.github.lonamiwebs.stringlate.activities.translate.TranslateActivity.doExportToSd(TranslateActivity.java:644)
	at io.github.lonamiwebs.stringlate.activities.translate.TranslateActivity.doExportToSd(TranslateActivity.java:585)
	at io.github.lonamiwebs.stringlate.activities.translate.TranslateActivity.onActivityResult(TranslateActivity.java:380)
	at android.app.Activity.dispatchActivityResult(Activity.java:6937)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4137)
	... 9 more
```

**Comment by Lonami** [comment]
Thanks for the incredibly detailed report. I thought `':'` wasn't a valid character when naming a string, so I used it for my own purposes when it comes down to translating `<string-array>`, I guess a bad assumption if that's really the case.

**Comment by Lonami** [comment]
#165 is kind of similar. Also has `ClassCastException` regarding arrays.

**Comment by ludoux** [comment]
Could you fix it to make the app "try its best" to export data file(e.g. the items without `:` or sth like this), not just crash without exporting anything? Export function should works well under any condition, especially this is a tool app for translation...
In fact, I exported the repo as zip file and found the string.xml manually in order to get the translation file...
Thanks for your job. It's a nice app.

**Comment by Lonami** [comment]
[`values/strings.xml`](https://github.com/T-Rex96/Easy_xkcd/blob/c2f049b35dfc238246a05e5dab13fead12eb43b9/app/src/main/res/values/strings.xml#L136-L140):
```xml
    <string-array name="pref_orientation">
        <item>Default</item>
        <item>Portrait</item>
        <item>Landscape</item>
</string-array>
```

[`zh-rCN/strings.xml`](https://github.com/T-Rex96/Easy_xkcd/blob/c2f049b35dfc238246a05e5dab13fead12eb43b9/app/src/main/res/zh-rCN/strings.xml#L192):
```xml
<string name="pref_orientation" modified="true">屏幕方向</string>
```

I have no idea how Android handles this. I can't see any reference to `modified="true"` on https://developer.android.com/guide/topics/resources/string-resource.html either. Guess I'll just convert it to a string array.

**Comment by Lonami** [comment]
> I thought `':'` wasn't a valid character when naming a string

I misunderstood back then, I just reviewed and the strings don't use `':'` so I think it's safe to consider this fixed now. The application will now try its best, thanks for the report and sorry for the delay :)

**Comment by Lonami** [comment]
Wait. I only tested with exporting, not writing.

**Comment by Lonami** [comment]
I just noticed the repository doesn't use `values-locale` to save the string, it just uses `locale`… That's bad. I thought the resources *had* to be in `values-locale` but apparenly `locale` is enough.

**Comment by Lonami** [comment]
![image](https://user-images.githubusercontent.com/6297805/38414912-2419cf62-3990-11e8-81e4-c0cf7eeb5312.png)

Nevermind.

**Comment by Lonami** [comment]
Okay after an hour or so on this I noticed string files can have the same name but different type, so a single item for a name is okay and then you can also have an array with the same name. Stringlate doesn't handle this correctly and so it fails. There's no need to check for this exception.

**Comment by Lonami** [comment]
Spent all morning but hey it's fixed.

**Comment by ludoux** [comment]
Thanks and have a nice day!
