### ISSUE TITLE
Crash on 0.9 for a certain app

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#8]
Xperia 5.1.1
Not sure if fixed yet, discover-> search https://github.com/SecUSo/privacy-friendly-pedometer -> New locale-> something -> crash

```
D AndroidRuntime: Shutting down VM
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: io.github.lonamiwebs.stringlate, PID: 13631
E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator io.github.lonamiwebs.stringlate.classes.resources.Resources.iterator()' on a null object reference
E AndroidRuntime: 	at io.github.lonamiwebs.stringlate.activities.TranslateActivity.loadStringIDsSpinner(TranslateActivity.java:562)
E AndroidRuntime: 	at io.github.lonamiwebs.stringlate.activities.TranslateActivity.setCurrentLocale(TranslateActivity.java:594)
E AndroidRuntime: 	at io.github.lonamiwebs.stringlate.activities.TranslateActivity.access$400(TranslateActivity.java:45)
E AndroidRuntime: 	at io.github.lonamiwebs.stringlate.activities.TranslateActivity$4.onClick(TranslateActivity.java:292)
E AndroidRuntime: 	at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:157)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:211)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5373)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

**Comment by XyLoNaMiyX** [comment]
Fun fact: that's the application I wanted to translate before I came up with the idea for Stringlate 😆

I can reproduce the bug on v0.9, and on the current master branch. The problem occurs because their `strings.xml` file contains `<>` characters (i.e. `<a href="someurl">some text</a>` inside a `<string>`). These are indeed invalid XML characters, and `&lt;` and `&gt;` should be used for text instead.

**Comment by licaon-kter** [comment]
So, I should raise an issue there?

**Comment by XyLoNaMiyX** [comment]
No, it's fine. Stringlate should consider as correct whatever the Android build considers correct. I didn't expect that the build would work with those characters (I would swear I've seen warnings of it before), but since it works, we should just mimic the behavior.

**Comment by XyLoNaMiyX** [comment]
Thank you for testing the application in so much depth :)
